# This is a basic workflow to help you get started with Actions

name: CI

# トリガーを設定
on:
  push:
    branches:
      - main
      - develop
    # README のみh変更したときに実行されないように
    path-ignore:
      - Docs/**
      - README.md
  pull_request:
    branches: 
      - develop
    path-ignore:
      - Docs/**
      - README.md

env:
  DEVELOPER_DIR: /Applications/Xcode.app/Contents/Developer/

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: macOS-latest
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Install Bundled Gems
        run: make install-bundler
      - name: Install Mint
        run: brew install mint
      
      - name: Cache Mint package
      - name: Install Carthage frameworks
        run: make install-carthage
      - name: Generate Xcode project and install Pods
        run: make generate-xcodeproj
      
      - name: Xcode build
        run: make build-debug
      
      - name: Xcode test
        run: make test

